### ISSUE TITLE
crypt(): No salt parameter was specified

### ISSUE THREAD

**Issue by BLaranjeira** [yoosuf/DX-Auth#13]
Hello,
I am using your DX-Auth for academic proposes.
My problem is when I register a user. It gives me an error, but the registation works fine, tried for a couple days working on this error but cant find any solution.
Im using XAMPP + Codeigniter.
Do you know what's causing this error ?

A PHP Error was encountered

Severity: Notice

Message: crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.

Filename: libraries/DX_Auth.php

Line Number: 946

Backtrace:

File: C:\xampp\htdocs\pti\application\libraries\DX_Auth.php
Line: 946
Function: crypt

File: C:\xampp\htdocs\pti\application\controllers\Autenticacao.php
Line: 88
Function: register

File: C:\xampp\htdocs\pti\index.php
Line: 247
Function: require_once

Sorry for your time,

Bruno Laranjeira.

**Comment by yoosuf** [comment]
@BLaranjeira can you please send a pull request
